-- Portable conflict-waiver workflow tables.
-- Migration 000016 used MySQL-only ENUM, INDEX, FULLTEXT and COMMENT syntax,
-- so installations that were initially migrated on PostgreSQL can be missing
-- these tables even when their schema version is newer.

CREATE TABLE IF NOT EXISTS waiver_applications (
    id VARCHAR(36) PRIMARY KEY,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL,
    application_number VARCHAR(50) NOT NULL UNIQUE,
    conflict_check_id VARCHAR(64) NOT NULL,
    case_id VARCHAR(36) NULL,
    client_id VARCHAR(36) NOT NULL,
    lawyer_id VARCHAR(36) NOT NULL,
    waiver_type VARCHAR(40) NOT NULL,
    waiver_category VARCHAR(40) NOT NULL,
    conflict_summary TEXT NOT NULL,
    conflicts TEXT NULL,
    risk_assessment TEXT NULL,
    proposed_conditions TEXT NOT NULL,
    limitations TEXT NULL,
    monitoring_requirements TEXT NULL,
    reporting_requirements TEXT NULL,
    requested_effective_date TIMESTAMP NOT NULL,
    requested_expiry_date TIMESTAMP NULL,
    duration_days INTEGER NULL,
    rationale TEXT NOT NULL,
    supporting_evidence TEXT NULL,
    alternatives_considered TEXT NULL,
    client_representative_name VARCHAR(255) NOT NULL,
    client_representative_title VARCHAR(100) NULL,
    client_representative_contact VARCHAR(255) NULL,
    requesting_lawyer_name VARCHAR(255) NOT NULL,
    requesting_lawyer_title VARCHAR(100) NULL,
    supervising_lawyer_name VARCHAR(255) NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'DRAFT',
    submission_date TIMESTAMP NULL,
    review_priority VARCHAR(20) NOT NULL DEFAULT 'MEDIUM',
    current_stage VARCHAR(40) NULL,
    assigned_reviewer VARCHAR(36) NULL,
    review_deadline TIMESTAMP NULL,
    created_by VARCHAR(36) NOT NULL,
    updated_by VARCHAR(36) NULL
);

CREATE TABLE IF NOT EXISTS waiver_approval_records (
    id VARCHAR(36) PRIMARY KEY,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL,
    waiver_application_id VARCHAR(36) NOT NULL,
    approval_stage VARCHAR(100) NOT NULL,
    approver_id VARCHAR(36) NOT NULL,
    approver_name VARCHAR(255) NOT NULL,
    approver_title VARCHAR(100) NULL,
    approver_role VARCHAR(40) NOT NULL,
    decision VARCHAR(30) NOT NULL,
    decision_reason TEXT NOT NULL,
    decision_comments TEXT NULL,
    approved_conditions TEXT NULL,
    imposed_limitations TEXT NULL,
    monitoring_requirements TEXT NULL,
    reporting_requirements TEXT NULL,
    risk_assessment TEXT NULL,
    risk_mitigation_plan TEXT NULL,
    follow_up_actions TEXT NULL,
    approval_date TIMESTAMP NOT NULL,
    effective_date TIMESTAMP NULL,
    expiry_date TIMESTAMP NULL,
    next_review_date TIMESTAMP NULL,
    supporting_documents TEXT NULL,
    evidence_references TEXT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    FOREIGN KEY (waiver_application_id) REFERENCES waiver_applications(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS waiver_signatures (
    id VARCHAR(36) PRIMARY KEY,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL,
    waiver_application_id VARCHAR(36) NOT NULL,
    signer_type VARCHAR(20) NOT NULL,
    signer_name VARCHAR(255) NOT NULL,
    signer_title VARCHAR(100) NULL,
    signer_organization VARCHAR(255) NULL,
    signer_contact VARCHAR(255) NULL,
    signature_content TEXT NOT NULL,
    signed_statement TEXT NOT NULL,
    terms_accepted TEXT NULL,
    signature_method VARCHAR(30) NOT NULL,
    signature_algorithm VARCHAR(100) NULL,
    digital_signature_hash VARCHAR(500) NULL,
    signature_timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    verification_status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    verification_method VARCHAR(100) NULL,
    verification_result TEXT NULL,
    verified_at TIMESTAMP NULL,
    signer_ip_address VARCHAR(45) NULL,
    user_agent TEXT NULL,
    device_fingerprint VARCHAR(255) NULL,
    location_info TEXT NULL,
    signed_document_url VARCHAR(500) NULL,
    backup_document_url VARCHAR(500) NULL,
    certificate_url VARCHAR(500) NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    revocation_reason TEXT NULL,
    revocation_date TIMESTAMP NULL,
    FOREIGN KEY (waiver_application_id) REFERENCES waiver_applications(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS waiver_monitoring_records (
    id VARCHAR(36) PRIMARY KEY,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL,
    waiver_application_id VARCHAR(36) NOT NULL,
    monitoring_type VARCHAR(40) NOT NULL,
    monitoring_date TIMESTAMP NOT NULL,
    monitoring_period_start TIMESTAMP NULL,
    monitoring_period_end TIMESTAMP NULL,
    monitoring_items TEXT NULL,
    check_results TEXT NULL,
    findings TEXT NULL,
    observations TEXT NULL,
    current_risk_level VARCHAR(20) NULL,
    risk_trend VARCHAR(20) NULL,
    risk_factors TEXT NULL,
    risk_mitigation_status TEXT NULL,
    compliance_status VARCHAR(30) NOT NULL DEFAULT 'UNDER_REVIEW',
    compliance_issues TEXT NULL,
    corrective_actions TEXT NULL,
    conditions_compliance TEXT NULL,
    limitation_adherence TEXT NULL,
    barrier_effectiveness TEXT NULL,
    recommended_actions TEXT NULL,
    required_follow_up TEXT NULL,
    next_monitoring_date TIMESTAMP NULL,
    report_generated BOOLEAN NOT NULL DEFAULT FALSE,
    report_url VARCHAR(500) NULL,
    report_recipients TEXT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'SCHEDULED',
    monitored_by VARCHAR(36) NOT NULL,
    reviewed_by VARCHAR(36) NULL,
    FOREIGN KEY (waiver_application_id) REFERENCES waiver_applications(id) ON DELETE CASCADE
);
